### ISSUE TITLE
Issues with running code

### ISSUE THREAD

**Issue by alexcibridge** [jaimemartinagui/Hangman-in-Python#1]
There is a traceback error when using the code and has a cannot find the module called numpy

**Comment by GeorgeOrzanescu** [comment]
It would be useful  if u give a bit more detail of how are you using the code. For example, are u running the code in a virtual environment?

**Comment by jaimemartinagui** [comment]
@alexcibridge I assume you are refering to the dependencies. I have just included the requierements.txt file.

Thank you!

**Comment by jaimemartinagui** [comment]
@GeorgeOrzanescu it is ok if you run it in any python 3 environment, as far as you install the requirements.

Regards,

Jaime

**Comment by alexcibridge** [comment]
@jaimemartinagui Thank you just seen you added requirements file :)

**Comment by jaimemartinagui** [comment]
You are welcome. Thank you for reporting the problem. May I close the issue now?
